import p1_img from "../../assets/My_Assets/product_1.jpg";
import p2_img from "../../assets/My_Assets/product_2.jpg";
import p5_img from "../../assets/My_Assets/product_5.jpg";
import p6_img from "../../assets/My_Assets/product_6.jpg";
import p7_img from "../../assets/My_Assets/product_7.jpg";
import p8_img from "../../assets/My_Assets/product_8.jpg";
import p9_img from "../../assets/My_Assets/product_9.jpg";
import p10_img from "../../assets/My_Assets/product_10.jpg";
import p11_img from "../../assets/My_Assets/product_11.jpg";
import p12_img from "../../assets/My_Assets/product_12.jpg";
import p13_img from "../../assets/My_Assets/product_13.jpg";
import p14_img from "../../assets/My_Assets/product_14.jpg";
import p15_img from "../../assets/My_Assets/product_15.jpg";
import p17_img from "../../assets/My_Assets/product_17.jpg";
import p18_img from "../../assets/My_Assets/product_18.jpg";
import p19_img from "../../assets/My_Assets/product_19.jpg";
import p20_img from "../../assets/My_Assets/product_20.jpg";
import p21_img from "../../assets/My_Assets/product_21.jpg";
const products = [
    {
      id: "1",
      name: "Гаманець 1",
      category: "wallets",
      image: p1_img,
      new_price: 1500,
      old_price: 2000,
      description: "Stylish wallet for everyday use.",
      colors: ["black", "brown", "blue"],
    },
    {
      id: "2",
      name: "Сумка 1",
      category: "bags",
      image: p2_img,
      new_price: 2100,
      old_price: 3000,
      description: "Durable and fashionable bag.",
      colors: ["red", "black", "green"],
    },
    {
      id: "5",
      name: "Гаманець",
      category: "wallets",
      image: p5_img,
      new_price: 1800,
      old_price: 2500,
      description: "Elegant wallet",
      colors: ["brown", "tan", "blue"],
    },
    {
      id: "6",
      name: "Сумка",
      category: "wallet",
      image: p6_img,
      new_price: 1900,
      old_price: 2700,
      description: "Premium bag with additional compartments.",
      colors: ["gray", "black", "white"],
    },
    {
      id: "7",
      name: "Гаманець 4",
      category: "wallets",
      image: p7_img,
      new_price: 1750,
      old_price: 2400,
      description: "Fashionable wallet with ample space.",
      colors: ["black", "red", "brown"],
    },
    {
      id: "8",
      name: "Ремінь",
      category: "belts",
      image: p8_img,
      new_price: 5000,
      old_price: 2000,
      description: "Classic wallet with elegant design.",
      colors: ["black", "brown", "gray"],
    },
    {
      id: "9",
      name: "Гаманець 1",
      category: "wallets",
      image: p9_img,
      new_price: 1600,
      old_price: 2200,
      description: "Stylish belt for any occasion.",
      colors: ["black", "blue", "tan"],
    },
    {
      id: "10",
      name: "Гаманець 4",
      category: "wallet",
      image: p10_img,
      new_price: 1700,
      old_price: 2300,
      description: "Wallet with modern design.",
      colors: ["brown", "green", "gray"],
    },
    {
      id: "11",
      name: "Гаманець 5",
      category: "wallet",
      image: p11_img,
      new_price: 1600,
      old_price: 2200,
      description: "Compact wallet with minimalist look.",
      colors: ["black", "tan", "gray"],
    },
    {
      id: "12",
      name: "Гаманець 6",
      category: "wallet",
      image: p12_img,
      new_price: 1700,
      old_price: 2300,
      description: "Spacious wallet with multiple slots.",
      colors: ["brown", "blue", "black"],
    },
    {
      id: "13",
      name: "Рюкзак 1",
      category: "backpacks",
      image: p13_img,
      new_price: 1800,
      old_price: 2500,
      description: "Functional backpack with ergonomic straps.",
      colors: ["black", "green", "blue"],
    },
    {
      id: "14",
      name: "Гаманець 7",
      category: "wallet",
      image: p14_img,
      new_price: 5000,
      old_price: 2700,
      description: "Luxurious wallet made from high-quality material.",
      colors: ["black", "red", "brown"],
    },
    {
      id: "15",
      name: "Чоловічий одяг 1",
      category: "men's clothing",
      image: p15_img,
      new_price: 2000,
      old_price: 2800,
      description: "Trendy men's clothing with a modern style.",
      colors: ["blue", "gray", "white"],
    },
    {
      id: "17",
      name: "Гаманець 8",
      category: "wallet",
      image: p17_img,
      new_price: 1700,
      old_price: 2300,
      description: "Elegant wallet with a sophisticated look.",
      colors: ["brown", "black", "green"],
    },
    {
      id: "18",
      name: "Сумка 6",
      category: "bags",
      image: p18_img,
      new_price: 4000,
      old_price: 2700,
      description: "Chic bag with adjustable straps.",
      colors: ["black", "red", "blue"],
    },
    {
      id: "19",
      name: "Сумка 7",
      category: "bags",
      image: p19_img,
      new_price: 2000,
      old_price: 2800,
      description: "Versatile bag suitable for various occasions.",
      colors: ["green", "black", "gray"],
    },
    {
      id: "20",
      name: "Ремінь 2",
      category: "belts",
      image: p20_img,
      new_price: 1500,
      old_price: 2000,
      description: "Classic belt with adjustable buckle.",
      colors: ["black", "brown", "tan"],
    },
    {
      id: "21",
      name: "Гаманець 9",
      category: "wallet",
      image: p21_img,
      new_price: 1800,
      old_price: 2500,
      description: "Stylish wallet with elegant coating.",
      colors: ["black", "brown", "blue"],
    },
    {
      id: "22",
      name: "Сумка 8",
      category: "bags",
      image: p19_img,
      new_price: 1900,
      old_price: 2700,
      description: "Elegant bag with versatile design.",
      colors: ["black", "blue", "tan"],
    },
    {
      id: "23",
      name: "Ремінь 3",
      category: "belts",
      image: p8_img,
      new_price: 1600,
      old_price: 2200,
      description: "Premium belt with smooth finish.",
      colors: ["black", "gray", "green"],
    },
    {
      id: "24",
      name: "Гаманець 10",
      category: "wallets",
      image: p1_img,
      new_price: 1500,
      old_price: 2000,
      description: "Compact and durable wallet.",
      colors: ["brown", "tan", "gray"],
    },
    {
      id: "25",
      name: "Чоловічий одяг 2",
      category: "men's clothing",
      image: p15_img,
      new_price: 5000,
      old_price: 2800,
      description: "Classic men's clothing with a refined look.",
      colors: ["white", "green", "gray"],
    },
    {
      id: "26",
      name: "Рюкзак 2",
      category: "backpacks",
      image: p13_img,
      new_price: 2100,
      old_price: 3000,
      description: "Stylish backpack for everyday use.",
      colors: ["red", "gray", "blue"],
    },
    {
      id: "27",
      name: "Гаманець 11",
      category: "wallet",
      image: p21_img,
      new_price: 4800,
      old_price: 2500,
      description: "Stylish wallet with a modern look.",
      colors: ["brown", "black", "tan"],
    },
    {
      id: "28",
      name: "Сумка 9",
      category: "bags",
      image: p2_img,
      new_price: 4200,
      old_price: 3000,
      description: "Fashionable bag with multiple compartments.",
      colors: ["gray", "black", "brown"],
    },
    {
      id: "29",
      name: "Ремінь 4",
      category: "belts",
      image: p20_img,
      new_price: 1300,
      old_price: 1800,
      description: "Elegant belt for formal occasions.",
      colors: ["brown", "black", "gray"],
    },
    {
      id: "30",
      name: "Гаманець 12",
      category: "wallets",
      image: p14_img,
      new_price: 1900,
      old_price: 2700,
      description: "Luxurious wallet for special occasions.",
      colors: ["blue", "black", "tan"],
    },
];

  export default products;